"""Agrega soporte técnico y cambios en usuario

Revision ID: 6fc850b4d020
Revises: 982a7c8abbdc
Create Date: 2025-06-24 04:33:47.355285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc850b4d020'
down_revision: Union[str, None] = '982a7c8abbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patient_dni_key'), 'patient', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('patient_dni_key'), 'patient', ['dni'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
