"""crear tabla usuario

Revision ID: 982a7c8abbdc
Revises: bfb07b049cf2
Create Date: 2025-06-18 01:26:15.467017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982a7c8abbdc'
down_revision: Union[str, None] = 'bfb07b049cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinicdata', sa.Column('vit_b12', sa.Numeric(precision=6, scale=3), nullable=True))
    op.drop_column('clinicdata', 'uric_acid')
    op.drop_column('clinicdata', 'c_reactive_protein')
    op.drop_column('clinicdata', 'glycated_hemoglobin')
    op.drop_column('clinicdata', 'mmse')
    op.drop_column('clinicdata', 'thyrotropic_hormone')
    op.drop_column('clinicdata', 'sodium')
    op.drop_column('clinicdata', 'bmi')
    op.drop_column('clinicdata', 'vitamin_b12')
    op.drop_column('clinicdata', 'moca')
    op.drop_column('clinicdata', 'clock_drawing_test')
    op.drop_column('clinicdata', 'hemoglobin')
    op.drop_column('clinicdata', 'creatinine')
    op.drop_column('patientcomorbilites', 'fibromialgia')
    op.drop_column('patientcomorbilites', 'heart_disease')
    op.drop_column('patientcomorbilites', 'atherosclerosis')
    op.drop_column('patientcomorbilites', 'diabetes')
    op.drop_column('patientcomorbilites', 'acv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patientcomorbilites', sa.Column('acv', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patientcomorbilites', sa.Column('diabetes', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patientcomorbilites', sa.Column('atherosclerosis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patientcomorbilites', sa.Column('heart_disease', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patientcomorbilites', sa.Column('fibromialgia', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('creatinine', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('hemoglobin', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('clock_drawing_test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('moca', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('vitamin_b12', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('bmi', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('sodium', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('thyrotropic_hormone', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('mmse', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('glycated_hemoglobin', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('c_reactive_protein', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('clinicdata', sa.Column('uric_acid', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.drop_column('clinicdata', 'vit_b12')
    # ### end Alembic commands ###
